# Use an official MongoDB image as the base image
FROM mongo:latest

# Expose MongoDB on port 27018
EXPOSE 27018

# Start MongoDB with custom port when the container starts
CMD ["mongod", "--port", "27018"]
